{
	"version": 1774016261,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/limit.png",
		"images/uppertilemap.png",
		"images/doors-sheet0.png",
		"images/doors-sheet1.png",
		"images/ground1.png",
		"images/tiledbackground.png",
		"images/pain.png",
		"images/coins-sheet0.png",
		"images/door1-sheet0.png",
		"images/image-sheet0.png",
		"images/cover-sheet0.png",
		"images/themover-sheet0.png",
		"images/points.png",
		"media/gameover2.ogg",
		"media/oops3.ogg",
		"media/bump2.ogg",
		"media/coin_2.ogg",
		"media/mattoglseby - 1.ogg",
		"media/timemachine.m4a",
		"media/timemachine.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}